[package]
name = "pyr-lapper"
version = "0.1.0"
authors = ["Seth Stadick <sstadick@gmail.com>"]
edition = "2018"

[lib]
name = "pyr_lapper"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]

[dependencies]
ivtools = {path = "../ivtools"}
